---
- name: Create the Watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update containers every monday at 5:00 a.m.
    command: --schedule "0 0 5 * * 1"

- name: Create the Tautulli container
  docker_container:
    name: tautulli
    image: tautulli/tautulli
    restart_policy: unless-stopped
    ports:
      - "8181:8181"

- name: Create the Jackett container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    restart_policy: unless-stopped
    ports:
      - "9117:9117"

- name: Create the Sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    restart_policy: unless-stopped
    ports:
      - "8989:8989"

- name: Create the Radarr container
  docker_container:
    name: radarr
    image: linuxserver/radarr
    restart_policy: unless-stopped
    ports:
      - "7878:7878"
