---
- name: Ensures config directory exists
  file:
    path: "/volume1/docker/{{ item }}/config"
    state: directory
  loop:
     - jackett
     - ombi
     - radarr
     - sonarr
     - tautulli
     - transmission

- name: Create the Watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    # Update containers every monday at 5:00 a.m.
    command: --schedule "0 0 5 * * 1" --cleanup
    env:
      WATCHTOWER_NOTIFICATIONS: "{{ WATCHTOWER_NOTIFICATIONS }}"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL }}"
