---
- name: Create the Wekan network
  docker_network:
    name: wekan

- name: Create the Wekan container
  docker_container:
    name: wekan
    image: wekanteam/wekan
    restart_policy: unless-stopped
    networks:
      - name: wekan
    ports:
      - 8080:8080
    env:
      ROOT_URL: http://localhost:8080
      MONGO_URL: mongodb://mongo

- name: Create the Mongodb container
  docker_container:
    name: mongo
    image: mongo
    restart_policy: unless-stopped
    networks:
      - name: wekan

- name: Create the Watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update containers every monday at 5:00 a.m.
    command: --schedule "0 0 5 * * 1"

- name: Create the Tautulli container
  docker_container:
    name: tautulli
    image: tautulli/tautulli
    restart_policy: unless-stopped
    ports:
      - 8181:8181
