---
- name: Ensures config directory exists
  file:
    path: "/volume1/docker/{{ item }}/config"
    state: directory
  with_items:
     - jackett
     - ombi
     - radarr
     - sonarr
     - tautulli

- name: Create the Watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    # Update containers every monday at 5:00 a.m.
    command: --schedule "0 0 5 * * 1" --cleanup
    env:
      WATCHTOWER_NOTIFICATIONS: "{{ WATCHTOWER_NOTIFICATIONS }}"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL }}"

- name: Create the Tautulli container
  docker_container:
    name: tautulli
    image: linuxserver/tautulli
    restart_policy: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/tautulli/config:/config
      - /volume1/Plex/Library/Application Support/Plex Media Server/Logs:/logs:ro

- name: Create the Jackett container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    restart_policy: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/jackett/config:/config

- name: Create the Sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    restart_policy: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/sonarr/config:/config
      - /volume1/Downloads/TV Shows:/tv

- name: Create the Radarr container
  docker_container:
    name: radarr
    image: linuxserver/radarr
    restart_policy: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/radarr/config:/config
      - /volume1/Downloads/Movies:/movies

- name: Create the Ombi container
  docker_container:
    name: ombi
    image: linuxserver/ombi
    restart_policy: unless-stopped
    ports:
      - "3579:3579"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/ombi/config:/config
