---
- name: Create the Ombi container
  docker_container:
    name: ombi
    image: linuxserver/ombi
    restart_policy: unless-stopped
    ports:
      - "3579:3579"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/ombi/config:/config
